name: Build and test

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

jobs:

  build-and-test-windows:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x.x
    - name: Restore local tools
      run: dotnet tool restore
    - name: Build and test
      run: dotnet fake build -t runTests